In [ ]:
# Topics to be covered -
# (1) Filtering Dataframe
# (2) Usage of loc and iloc functions
# (3) Sorting Dataframe
# (4) Pivot tables
# (5) Feature Engineering

In [2]:
# Importing important libraries
import pandas as pd
import numpy as np

In [15]:

np.random.random(7).round(2)

array([0.37, 0.95, 0.73, 0.6 , 0.16, 0.16, 0.06])

In [9]:
np.random.random(7).round(2)

array([0.87, 0.6 , 0.71, 0.02, 0.97, 0.83, 0.21])

In [10]:
np.random.random(7).round(2)

array([0.18, 0.18, 0.3 , 0.52, 0.43, 0.29, 0.61])

In [11]:
np.random.random(7).round(2)

array([0.14, 0.29, 0.37, 0.46, 0.79, 0.2 , 0.51])

In [17]:
# Creating the dataset
np.random.seed(42)
df = pd.DataFrame({
    'Name' : ['Jane', 'John', 'Ashley', 'Mike', 'Emily', 'Jack', 'Catlin'],
    'Ctg' : ['A', 'A', 'C', 'B', 'B', 'C', 'B'],
    'Val' : np.random.random(7).round(2),
    'Val2' : np.random.randint(1, 10, size = 7)   
    # Hey np, use your random.randint function
    # Take starting point as 1 | ending point as 10
    # Between 1 and 10, give me 7 integer values
    # You are allowed to repeat the same integer multiple times/as many
    # times as you want - default behaviour
})
df.head()

Name Ctg   Val  Val2
0    Jane   A  0.37     8
1    John   A  0.95     5
2  Ashley   C  0.73     4
3    Mike   B  0.60     8
4   Emily   B  0.16     8

In [3]:
# Filtering according to logical operators
df[df['Val'] > 0.5]

Name Ctg   Val  Val2
0  Jane   A  0.54     6
1  John   A  0.62     5
5  Jack   C  0.97     2

In [4]:
# Logical Operator works on String ?
df[df['Name'] > 'Jane']

Name Ctg   Val  Val2
1  John   A  0.62     5
3  Mike   B  0.08     3

In [ ]:
# Logical Operators for strings will work : 
# Only names with alphabetical order greater than Jane will appear.

In [5]:
# Adding multiple conditions while filtering
df[(df['Val'] < 0.5) | (df['Val2'] == 7)]

Name Ctg   Val  Val2
2  Ashley   C  0.17     3
3    Mike   B  0.08     3
4   Emily   B  0.01     8
6  Catlin   B  0.13     8

In [6]:
# Adding multiple conditions while filtering
df[(df['Val'] < 0.5) & (df['Val2'] == 3)]

Name Ctg   Val  Val2
2  Ashley   C  0.17     3
3    Mike   B  0.08     3

In [20]:
df['Name'].isin(names)

0    False
1     True
2    False
3     True
4    False
5    False
6     True
Name: Name, dtype: bool

In [19]:
# isin() Operator
names = ['John', 'Catlin', 'Mike']
df[df['Name'].isin(names)]

Name Ctg   Val  Val2
1    John   A  0.95     5
3    Mike   B  0.60     8
6  Catlin   B  0.06     6

In [21]:
# Str accessor
df[df['Name'].str.startswith('J')]

Name Ctg   Val  Val2
0  Jane   A  0.37     8
1  John   A  0.95     5
5  Jack   C  0.16     3

In [ ]:
# List the names starting with A



In [9]:
# Str accessor
df[df['Name'].str.contains('y')]

Name Ctg   Val  Val2
2  Ashley   C  0.17     3
4   Emily   B  0.01     8

In [10]:
# Tilde Operator
df[~df['Name'].str.startswith('J')]

Name Ctg   Val  Val2
2  Ashley   C  0.17     3
3    Mike   B  0.08     3
4   Emily   B  0.01     8
6  Catlin   B  0.13     8

In [11]:
# nlargest
df.nlargest(3, 'Val')

Name Ctg   Val  Val2
5  Jack   C  0.97     2
1  John   A  0.62     5
0  Jane   A  0.54     6

In [13]:
# nsmallest
df.nsmallest(2, 'Val2')

Name Ctg   Val  Val2
5    Jack   C  0.97     2
2  Ashley   C  0.17     3

In [ ]:
# loc and iloc -
# loc : select rows and columns using labels
# iloc : select rows and columns using indices

In [14]:
# 4th and 5th row with all columns
df.iloc[3:5, :]

Name Ctg   Val  Val2
3   Mike   B  0.08     3
4  Emily   B  0.01     8

In [ ]:
# If the dataframe has integer index, the indices and labels of the rows are same.
# In such a scenario loc and iloc will do the same thing.

In [15]:
# 3rd and 4th row with all columns
df.loc[3:5, :]

Name Ctg   Val  Val2
3   Mike   B  0.08     3
4  Emily   B  0.01     8
5   Jack   C  0.97     2

In [16]:
# Changing the index
df.index = ['A','B','C','D','E','F','G']

In [17]:
# loc function
df.loc['B':'D', :]

Name Ctg   Val  Val2
B    John   A  0.62     5
C  Ashley   C  0.17     3
D    Mike   B  0.08     3

In [19]:
# loc function
df.iloc[1:3, :]

Name Ctg   Val  Val2
B    John   A  0.62     5
C  Ashley   C  0.17     3

In [20]:
# Sorting the dataframe
df.head()

Name Ctg   Val  Val2
A    Jane   A  0.54     6
B    John   A  0.62     5
C  Ashley   C  0.17     3
D    Mike   B  0.08     3
E   Emily   B  0.01     8

In [21]:
# Ordering rows in alphabetical order
df.sort_values(by = ['Name'])

Name Ctg   Val  Val2
C  Ashley   C  0.17     3
G  Catlin   B  0.13     8
E   Emily   B  0.01     8
F    Jack   C  0.97     2
A    Jane   A  0.54     6
B    John   A  0.62     5
D    Mike   B  0.08     3

In [22]:
# Sorting rows 
df.sort_values(by = ['Val'], ascending = False)

Name Ctg   Val  Val2
F    Jack   C  0.97     2
B    John   A  0.62     5
A    Jane   A  0.54     6
C  Ashley   C  0.17     3
G  Catlin   B  0.13     8
D    Mike   B  0.08     3
E   Emily   B  0.01     8

In [23]:
# Sorting rows 
df.sort_values(by = ['Val2'], ascending = True)

Name Ctg   Val  Val2
F    Jack   C  0.97     2
C  Ashley   C  0.17     3
D    Mike   B  0.08     3
B    John   A  0.62     5
A    Jane   A  0.54     6
E   Emily   B  0.01     8
G  Catlin   B  0.13     8

In [27]:
# Creating the dataset
df = pd.DataFrame({
    'Name' : ['Jane', 'John', 'Jack', 'Mike', 'Emily', 'Jack', 'Catlin'],
    'Ctg' : ['A', 'A', 'B', 'B', 'B', 'C', 'B'],
    'Val' : np.random.random(7).round(2),
    'Val2' : np.random.randint(1, 10, size = 7)
})
df.head()

Name Ctg   Val  Val2
0   Jane   A  0.78     8
1   John   A  0.78     2
2   Jack   B  0.73     2
3   Mike   B  0.08     5
4  Emily   B  0.71     6

In [28]:
# Sorting on multiple rows
df.sort_values(by = ['Name', 'Ctg'])

Name Ctg   Val  Val2
6  Catlin   B  0.16     5
4   Emily   B  0.71     6
2    Jack   B  0.73     2
5    Jack   C  0.97     7
0    Jane   A  0.78     8
1    John   A  0.78     2
3    Mike   B  0.08     5

In [29]:
# Sorting on multiple rows in different orders
df.sort_values(by = ['Name', 'Ctg'], ascending = [True, False])

Name Ctg   Val  Val2
6  Catlin   B  0.16     5
4   Emily   B  0.71     6
5    Jack   C  0.97     7
2    Jack   B  0.73     2
0    Jane   A  0.78     8
1    John   A  0.78     2
3    Mike   B  0.08     5

In [ ]:
# Pivot Tables

In [32]:
# Creating the dataframe
df = pd.DataFrame({
    'Product' : ['Carrots', 'Broccoli', 'Banana', 'Banana',
                'Beans', 'Orange', 'Broccoli', 'Banana'],
    'Category' : ['Vegetable', 'Vegetable', 'Fruit', 'Fruit',
                 'Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
    'Quantity' : [8,5,3,4,5,9,11,8],
    'Amount' : [270,239,617,384,626,610,62,90]
})
df.head()

Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626

In [33]:
# Pivot table with sum aggregator function
pivot = df.pivot_table(index = ['Product'],
                      values = ['Amount'],
                      aggfunc = 'sum')
print(pivot)

          Amount
Product         
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610


In [34]:
# Pivot table with sum aggregator function
pivot = df.pivot_table(index = ['Category'],
                      values = ['Amount'],
                      aggfunc = 'sum')
print(pivot)

           Amount
Category         
Fruit        1701
Vegetable    1197


In [35]:
# Pivot table with sum aggregator function
pivot = df.pivot_table(index = ['Product', 'Category'],
                      values = ['Amount'],
                      aggfunc = 'sum')
print(pivot)

                    Amount
Product  Category         
Banana   Fruit        1091
Beans    Vegetable     626
Broccoli Vegetable     301
Carrots  Vegetable     270
Orange   Fruit         610


In [36]:
# Getting mean, median, minimum sale 
# Pivot table with sum aggregator function
pivot = df.pivot_table(index = ['Category'],
                      values = ['Amount'],
                      aggfunc = ['mean', 'median', 'min'])
print(pivot)

             mean median    min
           Amount Amount Amount
Category                       
Fruit      425.25  497.0     90
Vegetable  299.25  254.5     62


In [37]:
# Getting mean, median, minimum sale 
# Pivot table with sum aggregator function
pivot = df.pivot_table(index = ['Product'],
                      values = ['Amount'],
                      aggfunc = ['mean', 'median', 'min'])
print(pivot)

                mean median    min
              Amount Amount Amount
Product                           
Banana    363.666667  384.0     90
Beans     626.000000  626.0    626
Broccoli  150.500000  150.5     62
Carrots   270.000000  270.0    270
Orange    610.000000  610.0    610
