In [2]:
# Importing important libraries
import numpy as np

In [3]:
# Question: # Create a numpy array from the list [1, 2, 3]
# Assign it to variable np_array_from_list

sample_list = [1,2,3]

np_array_from_list = np.array(sample_list)
np_array_from_list


array([1, 2, 3])

In [5]:
sample_dict = {'a': 1, 'b': 2, 'c': 3, 'd': 4}


In [ ]:
# dictionary 

# Create 2 arrays
# dictionary keys into one array - np_array_keys
# dictionary values into otherarray - np_array_values

# np_array_keys
# np_array_values

In [6]:
dict_k = np.array(list(sample_dict.keys()))

In [7]:
dict_k

array(['a', 'b', 'c', 'd'], dtype='<U1')

In [8]:
dict_v = np.array(list(sample_dict.values()))

In [9]:
dict_v

array([1, 2, 3, 4])

In [10]:
# Problem statement

sample_list

[1, 2, 3]

In [12]:
a_list = [1,2,3]
prod=np.prod(np.array(a_list))
print(prod)

6


In [ ]:
list(1,2,3)

In [17]:
sample_list_1

[5, 10, 15]

In [16]:
# Multiply each element of list by 5
# sample_list_into_5

sample_list_1 = [] 
for i in sample_list: 
    sample_list_1.append(i*5)
    


In [11]:
np_array_from_list

array([1, 2, 3])

In [13]:
# Multiply each element of array by 5
np_array_from_list * 5   # Vectorised operation

array([ 5, 10, 15])

In [18]:
sample_list

[1, 2, 3]

In [ ]:
# Add 100 to each element for the array np_array_from_list
np_array_from_list

In [19]:
my_list = [1,2,3]
prod = np.array(my_list) + 100
print(prod)

[101 102 103]


In [ ]:
[
    [0, 0, 0],
    [0, 0, 0]
]




In [21]:
np.zeros((2,3), dtype=np.int16)


# int16
# 

numpy.float64

In [ ]:
[
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1]
]

In [23]:
np.ones((3, 4))


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((3,4),dtype=np.int64)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [2]:
# Question: # Create a numpy array from the list [1, 2, 3]

a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
# Question 
a = np.array([1, 2, 3], dtype = complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [24]:
np.array([1,2,'ML', 4])

# What will be the datatype of the first element?



array(['1', '2', 'ML', '4'], dtype='<U21')

In [4]:
# Question 
a = np.array([1,2,'ML', 4])
print(a)
b = np.array([1,2,3,4])
print(b)

['1' '2' 'ML' '4']
[1 2 3 4]


In [5]:
# Question 
ary = np.array([1,2,3,5,8])
ary = ary + 1
print(ary[1])

3


In [6]:
# Question 
a = np.array([[1,2,3],[0,1,4]])
print(a.size)

6


In [7]:
# Question 
a = np.array([[1,2,3],[0,1,4]])
b = np.zeros((2,3), dtype=np.int16)
c = np.ones((2,3), dtype=np.int16)
d = a + b + c
print(d[1,2])

5


In [ ]:
# Matrix

[
    ['H', 'H', 'H'],
    ['H', 'H', 'H']
]




In [25]:
np.matrix((2,3))

matrix([[2, 3]])

In [26]:
np.full((2, 3),"H")

array([['H', 'H', 'H'],
       ['H', 'H', 'H']], dtype='<U1')

In [27]:
np.matrix('H')(3,2,)

ValueError: malformed node or string: <ast.Name object at 0x11f2983d0>

In [31]:
# Create a 3 by 4 matrix with randomly 
# generated integers between 50 and 100


[
    [52, 99, 87, 88],
    [88, 88, 86, 75],
    [95, 67, 68, 90]
    
]

[
    [53, 75, 56, 61],
    [88, 87, 89, 87],
    [95, 74, 57, 99]
    
]

[[52, 99, 87, 88], [88, 88, 86, 75], [95, 67, 68, 90]]

In [32]:
np.random.randint(low=50, high=100, size=(3,4))


array([[0, 0, 3, 2],
       [3, 0, 4, 0],
       [3, 4, 1, 1]])

In [36]:
from numpy import random 
np.random.seed(42)
output_list=random.randint(100, size=(5)) 
print(output_list)

[51 92 14 71 60]


In [28]:
np.arange(50,101)

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [29]:
np.arange(50,101)

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [30]:
np.arange(50,101)

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
# Padding

[1,2,3]
[4,5]
[6,7,8,9]

[6, 7, 8, 9]

In [ ]:
# ML algortihms need all the arrays 
# coming into it to be of the same size
[1,2,3]
[4,5]
[6,7,8,9]

# array of size 6


[1,2,3] => [-1, 0, 1, 2, 3, 0]
[4,5]   => [-1, 0, 4, 5, 0, 0]
[6,7,8,9] => [0, 0, 6, 7, 8, 9]


In [38]:
sample_list

[1, 2, 3]

In [ ]:
[1, 2, 3] => [0, 0, 1,2,3, 5]   # 6 element array

# first 2 elements as 0
# last element as 5

np.pad()

In [ ]:
[1,2,3] 
[]

In [39]:
np.pad(sample_list, (2, 1), 'constant', constant_values=(0, 5))

array([0, 0, 1, 2, 3, 5])