In [1]:
# Command for installing numpy
!pip install numpy

In [2]:
## Importing Numpy package
import numpy as np

In [3]:
np_weight = np.array([45,56,78,87,98])

In [4]:
np_weight

array([45, 56, 78, 87, 98])

In [5]:
list_we=[45,56,78,87,98]

In [6]:
type(np_weight)

numpy.ndarray

In [7]:
list_we

[45, 56, 78, 87, 98]

In [8]:
type(list_we)

list

In [9]:
# Difference between Numpy Arrays and Python Lists :
# (1) Less Memory Space Required
# (2) Faster Computation

In [10]:
import numpy as np
import time
size = 1000000  #Size of array 

### Declare python list
L1 = range(size)
L2 = range(size)

# declare two arrays
a1 = np.arange(size)  
a2 = np.arange(size)

## list
start = time.time()
result = [(x+y) for x,y in zip(L1 , L2)]
print("python list took :" ,(time.time()-start)*1000)

## numpy array
start = time.time()
result = a1 + a2
print("numpy array took :" ,(time.time() - start)*1000)

python list took : 147.78900146484375
numpy array took : 22.31597900390625


In [11]:
# Initializing from Python List
v = np.array([1,4,9,3,2])
print ('1D array in numpy is %s\n'%v)
print ('dtype of the numpy array is %s\n'%str(v.dtype))

1D array in numpy is [1 4 9 3 2]

dtype of the numpy array is int64



In [12]:
# Creating a numpy array from python list
python_list = [32,56,67]
np.array(python_list)

array([32, 56, 67])

In [13]:
# Matrix with zeros
mat_zeros = np.zeros(shape=(3,5))
print ('Zeros Matrix of shape %s is \n%s\n'%(mat_zeros.shape,mat_zeros))
mat_ones = np.ones(shape=(2,3))
print ('Ones Matrix of shape %s is \n%s\n'%(mat_ones.shape,mat_ones))

Zeros Matrix of shape (3, 5) is 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

Ones Matrix of shape (2, 3) is 
[[1. 1. 1.]
 [1. 1. 1.]]



In [14]:
np.zeros(shape = (4, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
# Matrix with 1's
np.ones(shape = (3, 3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [16]:
# Numpy array of a particular value
np.full(shape = (4, 4), fill_value = 8, dtype = int)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [17]:
# Numpy array of a particular value
np.full(shape = (4, 4), fill_value = 'Hello')

array([['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello'],
       ['Hello', 'Hello', 'Hello', 'Hello']], dtype='<U5')

In [18]:
np.full(shape = (4, 4), fill_value = 101, dtype = int)

array([[101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101],
       [101, 101, 101, 101]])

In [19]:
np_array  = np.array([3,5,"NAas",6])

In [20]:
np_array

array(['3', '5', 'NAas', '6'], dtype='<U21')

In [21]:
# Randn
mat3 = np.random.randn(3,4)
print ('matrix generated from numpy.random.randn is \n%s\n'%mat3)

matrix generated from numpy.random.randn is 
[[ 2.53588583  1.57832764 -0.21445678  0.15863982]
 [-1.9315059  -1.16662603  0.77820118 -0.37066033]
 [-1.01140516 -1.2005002  -1.45231684  0.21626133]]



In [22]:
# Rand
mat1 = np.random.rand(2,3)
print ('matrix generated from numpy.random.rand is \n%s\n'%mat1)

matrix generated from numpy.random.rand is 
[[0.04786461 0.62102906 0.5145035 ]
 [0.49127532 0.77480149 0.10656262]]



In [23]:
# Randn
np.random.seed(0)
np.random.randn(3,3,3)

array([[[ 1.76405235,  0.40015721,  0.97873798],
        [ 2.2408932 ,  1.86755799, -0.97727788],
        [ 0.95008842, -0.15135721, -0.10321885]],

       [[ 0.4105985 ,  0.14404357,  1.45427351],
        [ 0.76103773,  0.12167502,  0.44386323],
        [ 0.33367433,  1.49407907, -0.20515826]],

       [[ 0.3130677 , -0.85409574, -2.55298982],
        [ 0.6536186 ,  0.8644362 , -0.74216502],
        [ 2.26975462, -1.45436567,  0.04575852]]])

In [24]:
# Randint
mat2 = np.random.randint(low=0,high=2,size=(3,4))
print ('matrix generated from numpy.random.random is \n%s\n'%mat2)

matrix generated from numpy.random.random is 
[[0 0 0 1]
 [1 0 1 0]
 [0 1 0 1]]



In [25]:
# Randint
np.random.randint(low=0,high=8,size=(3,3))

array([[1, 7, 1],
       [1, 3, 6],
       [7, 3, 6]])

In [26]:
# arange()
np.arange(start = 5, stop = 50, step = 5, dtype = int)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [27]:
# arange()
v1 = np.arange(5)
print ('Creating a numpy array via arange (stop=5) : %s\n'%v1)
v2 = np.arange(2,5)
print ('Creating a numpy array via arange (start=2,stop=5) : %s\n'%v2)
v3 = np.arange(0,-10,-2)
print ('Creating a numpy array via arange (start=0,stop=-10,step=-2) : %s\n'%v3)

Creating a numpy array via arange (stop=5) : [0 1 2 3 4]

Creating a numpy array via arange (start=2,stop=5) : [2 3 4]

Creating a numpy array via arange (start=0,stop=-10,step=-2) : [ 0 -2 -4 -6 -8]



In [28]:
# Create the table of 4 using np.arange()
np.arange(start = 4, stop = 104, step = 4, dtype = int)

array([  4,   8,  12,  16,  20,  24,  28,  32,  36,  40,  44,  48,  52,
        56,  60,  64,  68,  72,  76,  80,  84,  88,  92,  96, 100])

In [29]:
# Padding Example with constant mode
arr = [1,2,3,4,5]
  
# padded array
pad_arr = np.pad(arr, (3, 2), 'constant', constant_values=(0, 7))
print(pad_arr)

[0 0 0 1 2 3 4 5 7 7]


In [30]:
# Padding Example with linear_ramp mode
arr = [1,2,3,4,5] 
  
# padding array using 'linear_ramp' mode
pad_arr = np.pad(arr, (3, 2), 'linear_ramp', end_values=(-4, 7))   
print(pad_arr)

[-4 -2  0  1  2  3  4  5  6  7]


In [31]:
# Padding Example with maximum mode
arr = [1,2,3,4,5]
  
# padding array using 'maximum' mode
pad_arr = np.pad(arr, (2,), 'maximum')
print(pad_arr)

[5 5 1 2 3 4 5 5 5]


In [32]:
# Flattening array using np.ravel()
array = np.arange(25).reshape(5, 5)
print("Original array : \n", array)
print("Processed array : \n", array.ravel())

Original array : 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
Processed array : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [33]:
# Getting the Occurence of 1 and 5 in a numpy array
arr = np.array([1,2,1,3,1,5,6,3,5,3,6,9,0,2])
print("Actual array :\n", arr)
print('Count of 1 :', np.count_nonzero(arr == 1))
print('Count of 5 :', np.count_nonzero(arr == 5))

Actual array :
 [1 2 1 3 1 5 6 3 5 3 6 9 0 2]
Count of 1 : 3
Count of 5 : 2


In [34]:
# Date Time Questions
# today
today = np.datetime64('today', 'D')
print("Today: ", today)
  
# yesterday
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yesterday: ", yesterday)
  
# for tomorrow
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ", tomorrow)

Today:  2022-11-20
Yesterday:  2022-11-19
Tomorrow:  2022-11-21


In [35]:
# Sorting based on one feature in numpy array
dtype = [('name', 'S20'), ('class', int), ('height', float)]
students = [('Abhishek', 5, 48.5), ('Shreya', 6, 52.5),('Shruti', 5, 42.10), ('Vijay', 5, 40.11)]

# Creating the actual array
students = np.array(students, dtype=dtype)   
print("Actual array :\n", students)

# Sorted array
print("Sort by height :\n", np.sort(students, order='height')) 

Actual array :
 [(b'Abhishek', 5, 48.5 ) (b'Shreya', 6, 52.5 ) (b'Shruti', 5, 42.1 )
 (b'Vijay', 5, 40.11)]
Sort by height :
 [(b'Vijay', 5, 40.11) (b'Shruti', 5, 42.1 ) (b'Abhishek', 5, 48.5 )
 (b'Shreya', 6, 52.5 )]


In [36]:
# Getting the indices of sorted elements 
employee_id = np.array([10015, 32176, 34813, 73265, 98541, 10876, 35456])
print("Original array :\n", employee_id)

# Getting the indices of sorted elements
i = np.argsort(employee_id)
print("Indices of the sorted elements of a given array : \n", i)

Original array :
 [10015 32176 34813 73265 98541 10876 35456]
Indices of the sorted elements of a given array : 
 [0 5 1 2 6 3 4]


In [37]:
# Outer Cross Product
# Creating numpy arrays
a = [[4, 7], [3, 4]]
b = [[2, 8], [1, 6]]
print("Actual Matrix : \n", a)
print("Actual Matrix : \n", b)

# Outer Cross Product
res = np.outer(a, b)
print("Outer product of two vectors : \n", res)

Actual Matrix : 
 [[4, 7], [3, 4]]
Actual Matrix : 
 [[2, 8], [1, 6]]
Outer product of two vectors : 
 [[ 8 32  4 24]
 [14 56  7 42]
 [ 6 24  3 18]
 [ 8 32  4 24]]


In [38]:
# Outer Product
# Creating numpy arrays
a = [[4, 7], [3, 4]]
b = [[2, 8], [1, 6]]
print("Actual Matrix : \n", a)
print("Actual Matrix : \n", b)

# Outer Cross Product
res = np.outer(a, b)
print("Outer product of two vectors : \n", res)

Actual Matrix : 
 [[4, 7], [3, 4]]
Actual Matrix : 
 [[2, 8], [1, 6]]
Outer product of two vectors : 
 [[ 8 32  4 24]
 [14 56  7 42]
 [ 6 24  3 18]
 [ 8 32  4 24]]


In [39]:
# Cross Product
# Creating numpy arrays
a = [[4, 7], [3, 4]]
b = [[2, 8], [1, 6]]
print("Actual Matrix : \n", a)
print("Actual Matrix : \n", b)

# Outer Cross Product
res = np.cross(a, b)
print("Cross product of two vectors : \n", res)

Actual Matrix : 
 [[4, 7], [3, 4]]
Actual Matrix : 
 [[2, 8], [1, 6]]
Cross product of two vectors : 
 [18 14]


In [40]:
# creating a 3X3 Numpy matrix
arr = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

# Displaying the Matrix
print("Actual Matrix : \n", arr)

# Trace of a matrix
trace = np.trace(arr)
print("Trace of given matrix : ", trace)

# Diagonal elements of a matrix
diag = np.diagonal(arr)
print("Diagonal elements of given matrix : ", diag)
print('Sum of diagonal elements : ', sum(diag))

Actual Matrix : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Trace of given matrix :  15
Diagonal elements of given matrix :  [1 5 9]
Sum of diagonal elements :  15


In [41]:
# Array Reshaping
arr = np.arange(16)
print('Actual array :\n', arr)

# Reshaping
arr_mod = arr.reshape(4,2,2)
print('Modified array :\n', arr_mod)

Actual array :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Modified array :
 [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]


In [42]:
# Elements divisible by 4
arr = np.arange(start = 4, stop = 101, step = 4, dtype = int).reshape(5, -1)
print('Output array :\n', arr)

Output array :
 [[  4   8  12  16  20]
 [ 24  28  32  36  40]
 [ 44  48  52  56  60]
 [ 64  68  72  76  80]
 [ 84  88  92  96 100]]


In [43]:
# Getting common elements 
arr1 = np.array([2,4,6,8,10])
arr2 = np.array([3,6,9])
  
# Common values between two arrays
print('Common intersecting values :', np.intersect1d(arr1, arr2))

Common intersecting values : [6]


In [44]:
# Checking the data type of the above arrays
print('Data Type of the numpy array 1 : ', arr1.dtype)
print('Data Type of the numpy array 2 : ', arr2.dtype)

Data Type of the numpy array 1 :  int64
Data Type of the numpy array 2 :  int64


In [45]:
# Converting the data type of above arrays to float
arr1 = arr1.astype(float)
arr2 = arr2.astype(float)

# Checking the data type of the above arrays
print('Array 1 :\n', arr1)
print('Data Type of the numpy array 1 : ', arr1.dtype)
print('Array 2 :\n', arr2)
print('Data Type of the numpy array 2 : ', arr2.dtype)

Array 1 :
 [ 2.  4.  6.  8. 10.]
Data Type of the numpy array 1 :  float64
Array 2 :
 [3. 6. 9.]
Data Type of the numpy array 2 :  float64


In [46]:
# Slicing Example
arr = np.arange(50)
print('Getting the first 20 elements :\n', arr[:20])

arr = np.arange(50).reshape(10, 5)
print('Element at position (1, 2) : ', arr[1, 2])
print('Elements from 2nd row :\n', arr[1, :])

Getting the first 20 elements :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
Element at position (1, 2) :  7
Elements from 2nd row :
 [5 6 7 8 9]


In [47]:
# View the no. of dimensions of the matrix
a = np.array([[5,10,15],
              [20,25,20]])
print('Array :','\n',a)
print('Dimensions :','\n',a.ndim)

Array : 
 [[ 5 10 15]
 [20 25 20]]
Dimensions : 
 2


In [48]:
# view the no. of rows and columns in matrix
a = np.array([[1,2,3],
              [4,5,6]])
print('Array :','\n',a)
print('Shape :','\n',a.shape)
print('Rows = ',a.shape[0])
print('Columns = ',a.shape[1])

Array : 
 [[1 2 3]
 [4 5 6]]
Shape : 
 (2, 3)
Rows =  2
Columns =  3


In [49]:
a = np.array([[5,10,15],
              [20,25,20]])
print('Size of array :',a.size)

Size of array : 6


In [50]:
# Exercise 1
a = np.random.randint(27, size = (3,3,3))
print('Number of elements in a : ', a.size)

Number of elements in a :  27


In [51]:
# Exercise 2 
b = np.random.randint(100, size = (10, 10))
print('Minimum value in b is : ', b.min())
print('Maximum value in b is : ', b.max())

Minimum value in b is :  0
Maximum value in b is :  99


In [52]:
# Difficult Question

In [53]:
# Indexing Questions
a = np.ones((7, 7))
print('The actual array :\n', a)
a[1:-1, 1:-1] = 0
print('The final output array :\n', a)

The actual array :
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
The final output array :
 [[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [54]:
# Padding Example
x = np.random.randint(1, 100, 9).reshape(3, 3)
print('The actual array :\n', x)

# Processed array
y = np.pad(x, pad_width = 2, mode = 'constant', constant_values = 0)
print('Output array :\n', y)

The actual array :
 [[33 71 86]
 [32 14 72]
 [57 25 80]]
Output array :
 [[ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0 33 71 86  0  0]
 [ 0  0 32 14 72  0  0]
 [ 0  0 57 25 80  0  0]
 [ 0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0]]


In [55]:
# Checker Board Example

In [56]:
# Creating a matrix with 0 values of shape (8, 8)
cb = np.zeros((8, 8), dtype = int)
print('Array with 0s:\n', cb)

Array with 0s:
 [[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


In [57]:
# Filling every alternate row with 1
cb[1::2, ::2] = 1
print('First Process Output :\n', cb)

First Process Output :
 [[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]


In [58]:
# Filling every alternate column with 1
cb[::2, 1::2] = 1
print('Final Output :\n', cb)

Final Output :
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [59]:
# Matrix Multiplication Example
mat_2_by_3 = np.random.randint(1, 10, (2, 3))
print('First array :\n', mat_2_by_3)
mat_3_by_5 = np.random.randint(10, 20, (3, 5))
print('Second array :\n', mat_3_by_5)

# Product
res = np.dot(mat_2_by_3, mat_3_by_5)
print('Final Output :\n', res)

First array :
 [[3 9 7]
 [7 2 7]]
Second array :
 [[18 18 13 12 13]
 [16 13 16 15 17]
 [10 18 14 16 15]]
Final Output :
 [[268 297 281 283 297]
 [228 278 221 226 230]]


In [60]:
# Lambda Function Example 1
marks = [('Physics', 92), ('Chemistry', 97), ('Maths', 95), ('Biology', 85)]
print("Original list of tuples:\n", marks)
marks.sort(key = lambda x: x[1])
print("Sorting the List of Tuples:\n", marks)

Original list of tuples:
 [('Physics', 92), ('Chemistry', 97), ('Maths', 95), ('Biology', 85)]
Sorting the List of Tuples:
 [('Biology', 85), ('Physics', 92), ('Maths', 95), ('Chemistry', 97)]


In [61]:
# Lambda Function Example 2
import datetime
now = datetime.datetime.now()
print('Current datetime :', now)
year = lambda x : x.year
month = lambda x : x.month
day = lambda x : x.day
t = lambda x : x.time()
print('Current Year :', year(now))
print('Current Month :',month(now))
print('Current Day :',day(now))
print('Current Time :',t(now))

Current datetime : 2022-11-20 14:42:22.915744
Current Year : 2022
Current Month : 11
Current Day : 20
Current Time : 14:42:22.915744


In [62]:
# Map Function Example 
team = ['Vijay', 'Sharvari', 'Abhishek', 'Rishab']
uppered_team = list(map(str.upper, team))
print(uppered_team)

['VIJAY', 'SHARVARI', 'ABHISHEK', 'RISHAB']


In [63]:
# Filter Function Example
# Sample data
marks = [66, 90, 68, 59, 76, 60, 88, 74, 81, 65, 92, 85]

# Function
def is_A_student(mark):
    return mark > 80
    
# Filtering the data
A_students = list(filter(is_A_student, marks))
print(A_students)

[90, 88, 81, 92, 85]


In [64]:
# Reduce Function Example 
from functools import reduce
print("The maximum element of the list is : ",end="")
print(reduce(lambda a,b : a if a > b else b,marks))

The maximum element of the list is : 92
